### ISSUE TITLE
Build CI failed

### ISSUE THREAD

**Issue by tekktrik** [CedarGroveStudios/Cedargrove_CircuitPython_RangeSlicer#2]
Happened to notice you updated this library on my feed, and saw that the latest build failed.  Happy to dig into it and fix it, if you'd like - I'm trying to find common issues and their solutions so I can eventually document them.

**Comment by CedarGroveStudios** [comment]
I welcome your help — haven’t had the cycles available to dig into the latest build issue. The only change was to correct an example file name. Thanks!

**Comment by CedarGroveStudios** [comment]
The error is looking like something from the inclusion of the non-volatile memory code during the Python package build phase:

```
sed: couldn't edit ./build_deps/circuitpython/data/nvm.toml: not a regular file
Error: Process completed with exit code 4.
```

I just encountered it again when working with another Community Bundle submittal (AirQualityTools).

**Comment by tekktrik** [comment]
Oh I finally remembered this issue - it's caused by an issue with part of a cloned CircuitPython repo, with the `nvm.toml` submodule.  We started using [a new way of changing the version string](https://github.com/tekktrik/workflows-circuitpython-libs/blob/eb96f9472844109706863d41a8e3c5015b24ed66/build/action.yml#L82) once this started occurring.

If you aren't tied to anything in your CI process, it might be worth updating to the new version that uses composite actions.  That way when they're updated you get those updates here for free.  We made that change there, and now the cookiecutter defaults to this.

**Comment by tekktrik** [comment]
Let me know if you want me to get you set up with the new CI files.  It may also cause a bump to the `pylint` version since the CI will now run with Python 3.X, which is now 3.11.

**Comment by CedarGroveStudios** [comment]
Yes, I'd appreciate an update to the new CI approach. I don't use CI for anything but cookiecutter pre-commit and submittals to the Community Bundle.

Is there a way for me to watch for this type of change?

**Comment by tekktrik** [comment]
You could watch for changes to the cookiecutter, but I'm also starting [a collection of issues and their fixes](https://github.com/tekktrik/circuitpython-infrastructure-notices) that you could watch.  That will be both a guide for common issues as well as a place to file issues for things as they come up.  The format will be primarily Markdown documents with details.  I aim to have it include both things that we change (e.g., updates to `pylint`) as well as changes made for reasons outside of our control (e.g., upgrading things to avoid deprecation).

**Comment by tekktrik** [comment]
I can also PR the changes to your other repo(s) if you link them here :)

**Comment by CedarGroveStudios** [comment]
Thanks! That will be a real labor saver!

... from the Community Bundle Library List (19 of 'em):

[CircuitPython_AD5245](https://github.com/CedarGroveStudios/CircuitPython_AD5245.git) A driver for the AD5245 digital potentiometer.

[CircuitPython_AD9833](https://github.com/CedarGroveStudios/CircuitPython_AD9833.git) A driver for the AD9833 Programmable Waveform Generator.

[CircuitPython_DRV8830](https://github.com/CedarGroveStudios/CircuitPython_DRV8830.git) A driver for the DRV8830 DC motor controller.

[CircuitPython_NAU7802](https://github.com/CedarGroveStudios/CircuitPython_NAU7802.git) A driver for the NAU7802 24-bit ADC.

[CircuitPython_AirQualityTools](https://github.com/CedarGroveStudios/CircuitPython_AirQualityTools.git) Calculate PM2.5 and CO2 air quality levels. 

[CircuitPython_ColorFader](https://github.com/CedarGroveStudios/CircuitPython_ColorFader.git) Brightness and gamma adjustment of an integer RGB color value.

[CircuitPython DST_Adjuster](https://github.com/CedarGroveStudios/CircuitPython_DST_Adjuster.git) Adjust struct time to North American Daylight Saving Time (DST). 

[CircuitPython LeapYear](https://github.com/CedarGroveStudios/CircuitPython_LeapYear.git) Confirms whether a specified year is a leap year. 

[CircuitPython_MIDI_Tools](https://github.com/CedarGroveStudios/CircuitPython_MIDI_Tools.git) A collection of methods for processing MIDI notes and Control Change codes.

[CircuitPython_OhmsLaw](https://github.com/CedarGroveStudios/CircuitPython_OhmsLaw.git) Calculate an Ohm’s Law result from two input parameters.

[CircuitPython PaletteFader](https://github.com/CedarGroveStudios/CircuitPython_PaletteFader.git) Color palette and list brightness setter and normalizer tool. 

[CircuitPython PaletteFilter](https://github.com/CedarGroveStudios/CircuitPython_PaletteFilter.git) Replace color index values in a displayio.Palette object.

[CircuitPython PaletteSlice](https://github.com/CedarGroveStudios/CircuitPython_PaletteSlice.git) Wrap a displayio.Palette object to permit list-like slicing. 

[CircuitPython_PunkConsole](https://github.com/CedarGroveStudios/CircuitPython_PunkConsole.git) Emulate the Atari Punk Console.

[CircuitPython_RangeSlicer](https://github.com/CedarGroveStudios/CircuitPython_RangeSlicer.git) Scale a range of input values into quantized range using hysteresis for noise reduction.

[CircuitPython_RGB_SpectrumTools](https://github.com/CedarGroveStudios/CircuitPython_RGB_SpectrumTools.git) Methods and classes for converting a normalized spectral index to RGB color values.

[CircuitPython_ShadowWatcher](https://github.com/CedarGroveStudios/CircuitPython_ShadowWatcher.git) Detects a shadow cast over an analog light sensor.

[CircuitPython_TemperatureTools](https://github.com/CedarGroveStudios/CircuitPython_TemperatureTools.git) A collection of Dew Point, Heat Index, and temperature unit helpers.

[CircuitPython_TouchCalibrator](https://github.com/CedarGroveStudios/CircuitPython_TouchCalibrator.git) A resistive touchscreen calibrator for Adafruit built-in and TFT FeatherWing displays.
